# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8ce208c03fd230ab052a7b1a2fc643001c1599bae016341567dd2ac845127a53447853d7e5a37aadc3d5e7afe47fc82d430cb0fee9e635ac506a3e9d107c44

test:
  secret_key_base: 6419d2212db863fdbb3855a2b798b9c3621691652bce6bf56966096a573342886b33f7665166f518f3a83e3fc306958447e403237c5b54dfa541f1d6045cfaac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
